[golang worker]  (bugfix: cursing) Dude. Fuck higher-order functions in Go.
- /typechecking nightmares



bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:57: non-declaration statement outside function body
worker/worker.go:57: syntax error: unexpected name, expecting semicolon or newline
worker/worker.go:59: non-declaration statement outside function body
worker/worker.go:60: non-declaration statement outside function body
worker/worker.go:61: non-declaration statement outside function body
worker/worker.go:62: syntax error: unexpected }
worker/worker.go:64: non-declaration statement outside function body
worker/worker.go:64: syntax error: unexpected name, expecting semicolon or newline
worker/worker.go:66: non-declaration statement outside function body
worker/worker.go:69: non-declaration statement outside function body
worker/worker.go:69: too many errors
bash-3.2$ gitx
bash-3.2$ gitx
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:57: non-declaration statement outside function body
worker/worker.go:57: syntax error: unexpected name, expecting semicolon or newline
worker/worker.go:59: non-declaration statement outside function body
worker/worker.go:60: non-declaration statement outside function body
worker/worker.go:61: non-declaration statement outside function body
worker/worker.go:62: syntax error: unexpected }
worker/worker.go:64: non-declaration statement outside function body
worker/worker.go:64: syntax error: unexpected name, expecting semicolon or newline
worker/worker.go:66: non-declaration statement outside function body
worker/worker.go:69: non-declaration statement outside function body
worker/worker.go:69: too many errors
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:57: non-declaration statement outside function body
worker/worker.go:57: syntax error: unexpected name, expecting semicolon or newline
worker/worker.go:59: non-declaration statement outside function body
worker/worker.go:60: non-declaration statement outside function body
worker/worker.go:61: non-declaration statement outside function body
worker/worker.go:62: syntax error: unexpected }
worker/worker.go:64: non-declaration statement outside function body
worker/worker.go:64: syntax error: unexpected name, expecting semicolon or newline
worker/worker.go:66: non-declaration statement outside function body
worker/worker.go:69: non-declaration statement outside function body
worker/worker.go:69: too many errors
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:59: non-declaration statement outside function body
worker/worker.go:59: syntax error: unexpected name, expecting semicolon or newline
worker/worker.go:61: non-declaration statement outside function body
worker/worker.go:62: non-declaration statement outside function body
worker/worker.go:63: non-declaration statement outside function body
worker/worker.go:64: syntax error: unexpected }
worker/worker.go:66: non-declaration statement outside function body
worker/worker.go:66: syntax error: unexpected name, expecting semicolon or newline
worker/worker.go:68: non-declaration statement outside function body
worker/worker.go:71: non-declaration statement outside function body
worker/worker.go:71: too many errors
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:59: non-declaration statement outside function body
worker/worker.go:59: syntax error: unexpected name, expecting semicolon or newline
worker/worker.go:61: non-declaration statement outside function body
worker/worker.go:62: non-declaration statement outside function body
worker/worker.go:63: non-declaration statement outside function body
worker/worker.go:64: syntax error: unexpected }
worker/worker.go:66: non-declaration statement outside function body
worker/worker.go:66: syntax error: unexpected name, expecting semicolon or newline
worker/worker.go:68: non-declaration statement outside function body
worker/worker.go:71: non-declaration statement outside function body
worker/worker.go:71: too many errors
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:28: undefined: Time
worker/worker.go:29: undefined: Time
worker/worker.go:47: undefined: Time
worker/worker.go:57: undefined: net
worker/worker.go:62: defer requires function call, not conversion
worker/worker.go:70: too many arguments to return
worker/worker_pool.go:72: go requires function call, not conversion
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:47: undefined: Time
worker/worker.go:57: undefined: net
worker/worker.go:62: defer requires function call, not conversion
worker/worker.go:68: cannot use worker.Body (type string) as type io.Reader in function argument:
	string does not implement io.Reader (missing Read method)
worker/worker.go:69: cannot use func literal (type func()) as type Responder in function argument
worker/worker.go:70: too many arguments to return
worker/worker.go:78: worker.NumberOfRequestss undefined (type *Worker has no field or method NumberOfRequestss)
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:57: undefined: net
worker/worker.go:62: defer requires function call, not conversion
worker/worker.go:68: cannot use worker.Body (type string) as type io.Reader in function argument:
	string does not implement io.Reader (missing Read method)
worker/worker.go:69: cannot use func literal (type func()) as type Responder in function argument
worker/worker.go:70: too many arguments to return
worker/worker.go:78: worker.NumberOfRequestss undefined (type *Worker has no field or method NumberOfRequestss)
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:57: undefined: net
worker/worker.go:60: defer requires function call, not conversion
worker/worker.go:66: cannot use worker.Body (type string) as type io.Reader in function argument:
	string does not implement io.Reader (missing Read method)
worker/worker.go:67: cannot use func literal (type func()) as type func() <T> in function argument
worker/worker.go:68: too many arguments to return
worker/worker.go:76: worker.NumberOfRequestss undefined (type *Worker has no field or method NumberOfRequestss)
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:58: undefined: net.Response
worker/worker.go:61: defer requires function call, not conversion
worker/worker.go:67: cannot use worker.Body (type string) as type io.Reader in function argument:
	string does not implement io.Reader (missing Read method)
worker/worker.go:68: cannot use func literal (type func()) as type func() <T> in function argument
worker/worker.go:69: too many arguments to return
worker/worker.go:77: worker.NumberOfRequestss undefined (type *Worker has no field or method NumberOfRequestss)
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:58: undefined: net.Response
worker/worker.go:67: cannot use worker.Body (type string) as type io.Reader in function argument:
	string does not implement io.Reader (missing Read method)
worker/worker.go:68: cannot use func literal (type func()) as type func() <T> in function argument
worker/worker.go:69: too many arguments to return
worker/worker.go:77: worker.NumberOfRequestss undefined (type *Worker has no field or method NumberOfRequestss)
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:59: undefined: net.Response
worker/worker.go:69: cannot use func literal (type func()) as type func() <T> in function argument
worker/worker.go:70: too many arguments to return
worker/worker.go:78: worker.NumberOfRequestss undefined (type *Worker has no field or method NumberOfRequestss)
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:59: syntax error: unexpected ), expecting (
worker/worker.go:61: non-declaration statement outside function body
worker/worker.go:62: non-declaration statement outside function body
worker/worker.go:63: non-declaration statement outside function body
worker/worker.go:64: syntax error: unexpected }
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:6: imported and not used: "net"
worker/worker.go:61: responder() used as value
worker/worker.go:71: too many arguments to return
worker/worker.go:79: worker.NumberOfRequestss undefined (type *Worker has no field or method NumberOfRequestss)
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:6: imported and not used: "net"
worker/worker.go:61: assignment count mismatch: 2 = 1
worker/worker.go:70: cannot use func literal (type func()) as type func() interface {} in function argument
worker/worker.go:71: too many arguments to return
worker/worker.go:79: worker.NumberOfRequestss undefined (type *Worker has no field or method NumberOfRequestss)
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:6: imported and not used: "net"
worker/worker.go:59: final function parameter must have type
worker/worker.go:61: assignment count mismatch: 2 = 1
worker/worker.go:71: too many arguments to return
worker/worker.go:79: worker.NumberOfRequestss undefined (type *Worker has no field or method NumberOfRequestss)
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:6: imported and not used: "net"
worker/worker.go:62: resp.Body undefined (type interface {} has no field or method Body)
worker/worker.go:63: resp.Status undefined (type interface {} has no field or method Status)
worker/worker.go:63: resp.Headers undefined (type interface {} has no field or method Headers)
worker/worker.go:63: resp.Body undefined (type interface {} has no field or method Body)
worker/worker.go:70: cannot use func literal (type func()) as type func() (interface {}, error) in function argument
worker/worker.go:71: too many arguments to return
worker/worker.go:79: worker.NumberOfRequestss undefined (type *Worker has no field or method NumberOfRequestss)
bash-3.2$ go run stressd.go
# stressd/worker
worker/worker.go:62: undefined: net.Response
worker/worker.go:71: cannot use func literal (type func()) as type func() (interface {}, error) in function argument
worker/worker.go:72: too many arguments to return
worker/worker.go:80: worker.NumberOfRequestss undefined (type *Worker has no field or method NumberOfRequestss)
bash-3.2$